### ISSUE TITLE
Date-time field can not process molgenis date-time format

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis-ui-form#166]
**How to reproduce:**

load form data with a field of type 'date-time' and a value in the format of the molgenis date-time format:

`YYYY-MM-DDTHH:mm:ssZZ`

for example: 

> 1985-08-12T06:12:13Z

**Expected:** 

The form validates the date-time as a valid date

**Actual:** 

The from validates the date-time as an invalid date

**Comment by sidohaakma** [comment]
Fixed by #198
