### ISSUE TITLE
Vue forms require you to fill in the id field when it's AUTO

### ISSUE THREAD

**Issue by LuukDijkhuis** [molgenis/molgenis-ui-form#185]
### How to Reproduce
1. As admin import [it_emx_autoid.xlsx](https://github.com/molgenis/molgenis/files/2266318/it_emx_autoid.xlsx)
2. Go to the Data Explorer settings and enable "Edit the data row using the forms edit plugin."
3. In the Data Explorer, go to _testAutoId_ and add a new row

### Expected behavior
The forms don't show the id field because it will be automatically filled in. 

### Observed behavior
The id field is shown and you can't submit the form without entering a value.

**Comment by sidohaakma** [comment]
Fixed by #193
