### ISSUE TITLE
several field validations not correct in new Forms

### ISSUE THREAD

**Issue by LuukDijkhuis** [molgenis/molgenis-ui-form#186]
### How to Reproduce
walk through the Vue Forms tab in the 7.0.0 Testplan

### Expected behaviors
- "." and "," not accepted for ints and longs
- ints should not accept > unsigned maxint32 values (2ˆ31-1 = 2147483647) (enter 35 digits, works fine) Couldn't check whether the server accepts it because "Save" doesn't work
- Nillable ints and longs accept non-numeric characters
- decimals accept both "." and "," - couldn't check whether the server accepts it because "Save" doesn't work
- validation message incorrect for several fields, expected "invalid value" or something - observed "This field is required"
- validation "on change" versus "on blur" inconsistent

**Comment by fdlk** [comment]
Fixed in 2.1.0
