### ISSUE TITLE
Vulnerability vue-form depends on extend 3.0.1

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis-ui-form#189]
### How to Reproduce
run yarn install

### Expected behavior
no unsafe dependancies

### Observed behavior
molgenis-ui-form > vue-form > extend@3.0.1 ( has vulnerability) ( [vue-from issue](https://github.com/fergaldoyle/vue-form/issues/117))

**Comment by sidohaakma** [comment]
Fixed by #194
