### ISSUE TITLE
Date field emits date-time even if only date part is set

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis-ui-form#195]
### How to Reproduce
Create form with a date field 
Set the date to 13 march 1976 ( 1976-13-03)

### Expected behavior
Event is emitted with the date as string object with the value '1976-13-03'

### Observed behavior
Sat Mar 13 1976 00:00:00 GMT+0100 (Central European Standard Time)

**Comment by sidohaakma** [comment]
Fixed by #198
