### ISSUE TITLE
TypeError logged in PhantomJS during unit tests

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-ui-form#222]
### How to Reproduce
Run unit tests

### Expected behavior
Clean log

### Observed behavior
> PhantomJS 2.1.1 (Linux 0.0.0) ERROR LOG: TypeError{stack: 'http://localhost:9876/base/index.js?ac7e791a234be3886b5f42689b9a40e54e03bca2:15767:33

**Comment by ConnorStroomberg** [comment]
closed by:
[Clean up error in test logging](https://github.com/molgenis/molgenis-ui-form/pull/224)
[fix null pointer due to missing parent component](https://github.com/molgenis/molgenis-ui-form/pull/223)
