### ISSUE TITLE
Auto generated dates not working

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-ui-form#255]
Causes https://github.com/molgenis/molgenis/issues/8235

### How to Reproduce
- Use the entity mapper to generate a form based in an entity field with an auto generated, required, non visible date field. ( server side generated field)
- Render the form in 'CREATE' mode

### Expected behavior
The field is not included in the form

### Observed behavior
The field is included in the form

**Comment by connoratrug** [comment]
@fdlk can you please update the issue report with a 'how to reproduce' within the context of the ui-form (demo), and include expected and observed behaviour.

**Comment by fdlk** [comment]
@connoratrug I created this issue as a placeholder for whatever needs fixing to fix the reported one. I don't know the details of the how to reproduce nor what exactly needs fixing yet. Getting that clear is indeed a good first step of fixing I think :)
