### ISSUE TITLE
Datetimes cannot be saved when not edited in forms

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis-ui-form#305]
### How to Reproduce
Load typetest into MOLGENIS
Edit a record
Save the same record, without making changes

### Expected behavior
Is saved correctly

### Observed behavior
In errorlog: 

Failed to parse attribute [xdatetime] value [Tue Aug 13 1985 08:12:13 GMT+0200 (Central European Summer Time)] as datetime. Valid datetime format is [YYYY-MM-DDThh:mm:ssZ]
at org.molgenis.api.data.RestService.convertDateTime(RestService.java:317)

**Comment by connoratrug** [comment]
Cannot reproduce in the context of the form repo

Tried: 
- Form with multiple data(time) fields
- In molgenis in data row edit; table with date, date-time, date-time with default

Can only reproduce in context of TypeTest table type

Created (copy) issu: https://github.com/molgenis/molgenis/issues/8671
