### ISSUE TITLE
Form invalidates briefly when validating

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-ui-form#306]
How to Reproduce
Do questionnaire testplan: QUESTREG006 with the c6 questionnaire.
Fill in questions

Expected behavior
Questions stay black because I don't add invalid values

Observed behavior
Questions blink red for a brief period of time when validating

https://github.com/molgenis/molgenis/issues/8666

**Comment by jvanveen** [comment]
Kan dit niet meer reproduceren. Ik sluit hem voor nu.
