### ISSUE TITLE
No length validation on Text fields

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-ui-form#344]
### How to Reproduce
enter 40.000 characters in a text field
save
go to navigatior
find entity (table)
select and press download

### Expected behavior
xlsx downloads

### Observed behavior
error given:

```
Download gefaald: Er is een fout opgetreden bij het schrijven van XLSX: The maximum length of cell contents (text) is 32,767 characters (NAV01)
```

**Comment by connoratrug** [comment]
The fact that exel export can not handle 40.000 char content does not mean the forms could block entering it info a field.
