### ISSUE TITLE
Schema test for double ID's generates errors in test-output

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis-ui-form#38]
Schema test for double ID's generates errors in test-output, due to incomplete mocking. 

**note**  
* Can be resolved by moving the validator-method in the FormComponent to an external module. 
* Mock the missing methods
* Move it to the 'methods'-tag in the FormComponent and test it by VUE-'shallow' test method

**Comment by Mark-de-Haan** [comment]
closed in #39
